name: Java CI

on: [push]

jobs:
  build:

    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-latest]
        jvm-version: [ 8, 11 ]

    steps:
      - uses: actions/checkout@v4

      - name: Install prerequisites
        run: |
          pip3 install --upgrade setuptools pip
          pip3 install conan

      - uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK ${{matrix.jvm-version}}
        uses: actions/setup-java@v1
        with:
          java-version: ${{matrix.jvm-version}}

      - name: Build with Gradle
        run: ./gradlew build #--info installDist

#      - uses: actions/upload-artifact@master
#        with:
#          name: vico
#          path: cli/build/install/vico
